### ISSUE TITLE
Put local copies of libs

### ISSUE THREAD

**Issue by elogy** [fsi-tue/fachschaftsempfaenger#44]
Currently, jQuery and fontawesome are loaded in through external CDNs. Depending on the network load, this slows down the initial load time of the site significantly.

One approach would be to include local copies of these libs.

**Comment by luoe** [comment]
jQuery is local since 9feaa1d392061d6721bbfc4990e1a5dc6878eb66
The problem with fontawesome ist that it loads a woff and a css file itself, should we also keep this local? This requires changes to the js file of fontawesome.

**Comment by elogy** [comment]
I think that would be a bit overkill. After all, fontawesome isn't that much of a burden on load time. Loading both the css and the woff takes about 30ms, whereas loading the calendar.html takes 279ms (what the hell?).

**Comment by luoe** [comment]
I don't think time is relevant (the mensa tile is also loading very slowly). It makes more sense if we look into the privacy aspect.
