### ISSUE TITLE
Tile: next meeting

### ISSUE THREAD

**Issue by elogy** [fsi-tue/fachschaftsempfaenger#82]
The calendar functionality has been implemented recently. However, the ability to show the _Sitzungstermin_ is still missing. 

There is a tile (`sitzung.html`) and a corresponding view (`def sitzung_tile()`) already, but there is absolutely no functionality in there.
What has to be done:
- Walk the calendar items of the public calendar (see `calendar.py`)
- Check for the first item where `item[2]` contains "Sitzung". (This should be renamed to "Sitzung FSI" and "Sitzung FSK, eventually)
- Grab the date, time and location for this item and pass it to the template. 

The template already looks for the variables `info.date`, `info.time` and `info.location`, the same applies for `kogni` instead of `info`, so if these are passed within the context, everything should work as expected. ... should.

**Comment by luoe** [comment]
@PhictionalOne, do you want to the take chance now?

**Comment by luoe** [comment]
Ah, I remember, you couldn't build the docker image, did you? @PhictionalOne

**Comment by PhictionalOne** [comment]
Should be solved here: e19cc1846a981c5314c2629cae00b9d33e27f18c

#ungetestetMüssteDasTun

(Sorry pushed to the wrong repo... Thougth that my push shorthand pushes to origin/my fork and not onto here)

**Comment by luoe** [comment]
Thanks a lot!
